/**
 * Supabase database type stub.
 *
 * In a fully typed setup this file is regenerated by:
 *   `supabase gen types typescript --local > src/types/supabase.ts`
 *
 * Until a project is linked, we provide an open shape so the app builds
 * without strict-mode errors. Replace with the generated file once you've
 * run the migrations against a real project.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Loose Database type — Supabase will infer `never` without this.
// This intentionally matches "any table, any shape" until generated types replace it.
// Uses an unrestricted record type deliberately to free downstream code of
// casting; once the schema is generated this becomes strict.
type AnyRow = Record<string, unknown>;

export interface Database {
  public: {
    Tables: {
      [table: string]: {
        Row: AnyRow;
        Insert: AnyRow;
        Update: AnyRow;
        Relationships: [];
      };
    };
    Views: Record<string, { Row: AnyRow; Relationships: [] }>;
    Functions: Record<string, { Args: AnyRow; Returns: unknown }>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, AnyRow>;
  };
}
