/**
 * User-facing metadata for each AI provider.
 *
 * Powers the BYOK settings page tutorials. Each provider has step-by-step
 * instructions that walk users through obtaining a key — written assuming
 * the user is non-technical (this app targets parents and kids).
 */

import type { AIProviderId, AIProviderInfo } from '@/types/core';

export const PROVIDER_INFO: Record<AIProviderId, AIProviderInfo> = {
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    tagline: 'Largest free tier — recommended primary',
    freeTier: '1,500 requests/day on Gemini 2.0 Flash; no credit card required',
    signupUrl: 'https://aistudio.google.com/apikey',
    setupSteps: [
      'Go to https://aistudio.google.com/apikey and sign in with your Google account.',
      'Click "Create API key" and choose "Create API key in new project".',
      'Copy the key (starts with "AIza..."). It will be a long string.',
      'Paste it below and click Save. The key is encrypted and only used by Math Wizard Pro.',
    ],
    defaultModel: 'gemini-2.0-flash',
    latencyTier: 'fast',
    qualityTier: 'high',
    strengths: ['Question generation', 'Step-by-step solutions', 'Generous free tier'],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    tagline: 'Fast + free — great for hints',
    freeTier: 'Free tier with daily request limits; very fast responses',
    signupUrl: 'https://console.groq.com/keys',
    setupSteps: [
      'Visit https://console.groq.com and sign up (free account, no credit card).',
      'Once logged in, go to the API Keys page in the left menu.',
      'Click "Create API Key", give it a name like "Math Wizard Pro".',
      'Copy the key (starts with "gsk_..."). Paste it below and Save.',
    ],
    defaultModel: 'llama-3.3-70b-versatile',
    latencyTier: 'instant',
    qualityTier: 'good',
    strengths: ['Fast responses', 'Hint generation', 'Free tier'],
  },
  cerebras: {
    id: 'cerebras',
    name: 'Cerebras',
    tagline: 'Fastest inference on the planet',
    freeTier: 'Free tier on llama-3.1-8b (default). Larger models require a paid plan.',
    signupUrl: 'https://cloud.cerebras.ai',
    setupSteps: [
      'Go to https://cloud.cerebras.ai and create a free account.',
      'After login, navigate to "API Keys" in your account.',
      'Click "Generate API Key" and copy the value.',
      'Paste it below and click Test key — by default we use llama-3.1-8b which is on the free tier.',
      'If you have access to bigger models, set CEREBRAS_MODEL=llama-3.3-70b in your env.',
    ],
    defaultModel: 'llama-3.1-8b',
    latencyTier: 'instant',
    qualityTier: 'good',
    strengths: ['Lowest latency', 'Reliable free tier on llama-3.1-8b', 'Good for hints'],
  },
  claude: {
    id: 'claude',
    name: 'Anthropic Claude',
    tagline: 'Best math reasoning — paid',
    freeTier: 'No persistent free tier; requires payment method, $5 starter credit',
    signupUrl: 'https://console.anthropic.com/',
    setupSteps: [
      'Visit https://console.anthropic.com and create an account.',
      'Add a payment method under Settings → Billing (a small starter credit is included).',
      'Go to API Keys and click "Create Key".',
      'Copy the key (starts with "sk-ant-..."). Paste it below and Save.',
    ],
    defaultModel: 'claude-haiku-4-5-20251001',
    latencyTier: 'fast',
    qualityTier: 'frontier',
    strengths: ['Best math reasoning', 'Tutor mode', 'Step-by-step solutions'],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    tagline: 'Broad coverage — paid',
    freeTier: 'No free tier; pay-as-you-go (gpt-4o-mini is ~$0.15 per 1M tokens)',
    signupUrl: 'https://platform.openai.com/api-keys',
    setupSteps: [
      'Sign in to https://platform.openai.com/ and add a payment method.',
      'Go to "API Keys" in the left sidebar.',
      'Click "Create new secret key" and choose "Restricted" → leave most permissions off, just enable "/v1/chat/completions".',
      'Copy the key (starts with "sk-..."). Paste it below and Save. You will not see this key again on OpenAI\'s site.',
    ],
    defaultModel: 'gpt-4o-mini',
    latencyTier: 'fast',
    qualityTier: 'high',
    strengths: ['Broad coverage', 'Reliable JSON output'],
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    tagline: 'Cheap + great at math',
    freeTier: 'No persistent free tier; very cheap pay-as-you-go (~10x cheaper than OpenAI)',
    signupUrl: 'https://platform.deepseek.com/',
    setupSteps: [
      'Create an account at https://platform.deepseek.com/.',
      'Add a payment method under Billing (small minimum).',
      'Go to "API keys" and click "Create new API key".',
      'Copy the key and paste it below.',
    ],
    defaultModel: 'deepseek-chat',
    latencyTier: 'normal',
    qualityTier: 'high',
    strengths: ['Strong math', 'Low cost', 'Long context'],
  },
  cloudflare: {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    tagline: 'Free Llama on the edge — same network as your app',
    freeTier: '10,000 Neurons/day free; runs Llama 3.3 70B and other open models',
    signupUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    setupSteps: [
      'Create a free Cloudflare account at https://dash.cloudflare.com/sign-up if you don\'t have one.',
      'Find your Account ID: dashboard right sidebar, copy "Account ID".',
      'Create an API token: My Profile → API Tokens → Create Token → use the "Workers AI" template (or custom token with permission "Account → Workers AI → Read").',
      'Combine them as a single string: <accountId>:<apiToken> (use a colon, no spaces).',
      'Paste the combined "<accountId>:<apiToken>" string below and Save.',
    ],
    defaultModel: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    latencyTier: 'instant',
    qualityTier: 'high',
    strengths: ['Free Llama', 'Edge-native if deployed on Cloudflare', 'No payment method'],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    tagline: 'Many free models, account-wide quota',
    freeTier: 'Free tier: ~50 requests/day TOTAL across all :free models. Top up $10 once → 1000 req/day. We auto-rotate across 13 free models for variety.',
    signupUrl: 'https://openrouter.ai/keys',
    setupSteps: [
      'Sign up at https://openrouter.ai/sign-in (Google or GitHub OAuth — no credit card needed for the basic free tier).',
      'Go to https://openrouter.ai/keys and click "Create Key".',
      'Name it "Math Wizard Pro", click Create.',
      'Copy the key (starts with "sk-or-...") and Save below.',
      'OPTIONAL: a one-time $10 top-up at https://openrouter.ai/credits unlocks 1000 free req/day (instead of 50). Best value if you\'ll use the app daily.',
    ],
    defaultModel: 'auto (rotates across free models)',
    latencyTier: 'fast',
    qualityTier: 'high',
    strengths: [
      'Free DeepSeek R1, Llama 3.3 70B, Qwen 72B, etc.',
      'Auto-rotates models for variety',
      '$10 one-time → 20× more free quota',
    ],
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral',
    tagline: 'European frontier models with a real free tier',
    freeTier: 'La Plateforme has a free experimental tier for Mistral Small + others',
    signupUrl: 'https://console.mistral.ai/api-keys',
    setupSteps: [
      'Sign up at https://console.mistral.ai (no credit card required for free tier).',
      'Verify your email, then visit https://console.mistral.ai/api-keys.',
      'Click "Create new key", give it a name, click Create.',
      'Copy the key and paste it below.',
    ],
    defaultModel: 'mistral-small-latest',
    latencyTier: 'fast',
    qualityTier: 'high',
    strengths: ['Free tier', 'Strong reasoning', 'European data residency'],
  },
  huggingface: {
    id: 'huggingface',
    name: 'Hugging Face',
    tagline: 'Free Llama via HF Inference Providers',
    freeTier: 'Monthly credit on HF Inference Providers (router auto-selects backend)',
    signupUrl: 'https://huggingface.co/settings/tokens',
    setupSteps: [
      'Create a free account at https://huggingface.co/join.',
      'Go to Settings → Access Tokens → "Create new token".',
      'Choose "Read" role, name it "Math Wizard Pro", click Generate.',
      'Copy the token (starts with "hf_..."). Paste it below.',
    ],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    latencyTier: 'normal',
    qualityTier: 'good',
    strengths: ['Free Llama', 'Many open models', 'Last-resort fallback'],
  },
};

export const PROVIDER_LIST: AIProviderId[] = [
  // Free tier (no credit card)
  'cloudflare',
  'gemini',
  'groq',
  'cerebras',
  'openrouter',
  'mistral',
  'huggingface',
  // Paid
  'claude',
  'deepseek',
  'openai',
];
