'use client';

import { cn } from '@/lib/utils';
import { PROVIDER_INFO } from '@/lib/ai/provider-info';
import type { AIProviderId } from '@/types/core';

/**
 * Small badge identifying who/what produced the current question.
 *
 * Possible labels (priority order):
 *   - Provider name: "Google Gemini", "Anthropic Claude", "Cloudflare AI", etc.
 *     Source tag: "your key" / "shared" / "cached"
 *   - "Curated bank" — for questions inserted by the seed script
 *   - Nothing (returns null) if no provider info is available
 *
 * The PROVIDER_INFO lookup gives us human-readable names + a tooltip.
 */
export interface ProviderBadgeProps {
  provider: string | null;
  source: string | null; // 'user' | 'admin' | 'cache' | 'curated' | null
  className?: string;
}

export function ProviderBadge({ provider, source, className }: ProviderBadgeProps) {
  if (!provider) return null;

  // Curated/seed-bank case: friendlier label.
  if (provider === 'curated' || source === 'curated') {
    return (
      <span
        title="Hand-curated question from the seed bank"
        className={cn(
          'inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-2xs font-semibold',
          'bg-spell-50 text-spell-800 border-spell-200',
          className,
        )}
      >
        <span aria-hidden>📚</span>
        <span>Curated bank</span>
      </span>
    );
  }

  const info = PROVIDER_INFO[provider as AIProviderId];
  const label = info?.name ?? provider;

  // Different visual cue per source:
  //   user → green ("your key")
  //   admin → gold ("shared")
  //   cache → purple ("cached")
  let suffix = '';
  let tone: 'leaf' | 'spell' | 'wizard' = 'wizard';
  if (source === 'user') { suffix = '· your key'; tone = 'leaf'; }
  else if (source === 'admin') { suffix = '· shared'; tone = 'spell'; }
  else if (source === 'cache') { suffix = '· cached'; tone = 'wizard'; }

  const colors = {
    leaf:  'bg-leaf-50 text-leaf-700 border-leaf-200',
    spell: 'bg-spell-50 text-spell-700 border-spell-200',
    wizard:'bg-wizard-50 text-wizard-700 border-wizard-200',
  };

  return (
    <span
      title={`Generated by ${label}${suffix ? ' (' + suffix.replace('· ', '') + ')' : ''}`}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-2xs font-semibold',
        colors[tone],
        className,
      )}
    >
      <span aria-hidden>✨</span>
      <span>{label}</span>
      {suffix && <span className="opacity-70 font-normal">{suffix}</span>}
    </span>
  );
}
